version: '3.4'

services:
  dataprocessor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro