version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  sensor.api:
    image: ${DOCKER_REGISTRY-}sensorapi
    build:
      context: .
      dockerfile: DockerfileSensor
    ports:
      - 3000:80
    depends_on:
      - sqldata

  dataprocessor.api:
    image: ${DOCKER_REGISTRY-}dataprocessorapi
    build:
      context: .
      dockerfile: DockerfileDataProcessor
    ports:
      - 3001:80

  profile.api:
    image: ${DOCKER_REGISTRY-}profileapi
    build:
      context: .
      dockerfile: DockerfileProfile
    ports:
      - 3002:80
    depends_on:
      - sqldata